Server:
  Port: 8900
  ReadTimeout: 15s
  WriteTimeout: 15s

API:
  BasePath: ""
  APITimeout: 15s
  EnableSwagger: true

Database:
  SlaveDSN: "postgres://postgres:1235813@localhost:5433/ums?sslmode=disable"
  MasterDSN: "postgres://postgres:1235813@localhost:5433/ums?sslmode=disable"
  RetryInterval: 10
  MaxIdleConn: 10
  MaxConn: 10
  ConnMaxLifetime: 10s

Kafka:
  Producer:
    Brokers:
      - localhost:9092
    MaxAttempt: 5
    Idempotent: true
  Topics:
    MasterDataUser:
      Value: "ums.masterdata-users"
      ErrorHandler: "Phase1"
      WithBackOff: true
    MasterDataVoter:
        Value: "ums.masterdata-voters"
        ErrorHandler: "Phase1"
        WithBackOff: true
    MasterDataKpuKota:
        Value: "ums.masterdata-kpu-kota"
        ErrorHandler: "Phase1"
        WithBackOff: true
    MasterDataKpuProvinsi:
        Value: "ums.masterdata-kpu-provinsi"
        ErrorHandler: "Phase1"
        WithBackOff: true

JWT:
  Secret: "^87adb2&91hnGaWd7"

GrpcServer:
  Port: 35000

Encryption:
  Key : "NZkrqmVGg6Bi4QbqGXbH9wz3Q0+NCGvMKA2j8hqD5eM="

BlockchainConfig:
  GanacheURL: "http://127.0.0.1:7545"
  VotechainAddress: "0xb83AFFf9a91098902F2Ecc028dAAC70c828148e2"
  ElectionManagerAddress: "0x72876493483a0b91465db0922Bb71E9687ccf5eE"
  KPUManagerAddress: "0xce5cF197fd4988ec9fDB5C00AaEea395dfdEBd46"
  VoterManagerAddress: "0xbf1457dACC8216d3dAF148B147c437bb6E445805"
  VotechainBaseAddress: "0x392DECCf6bc4C2bbe3682e31BD7210015F5E23DE"


Cors:
  AllowOrigins: "*"
  AllowMethods: "GET,POST,PUT,DELETE,OPTIONS"
  AllowHeaders: "Content-Type,Authorization"
  AllowCredentials: false
  ExposeHeaders: "X-Custom-Header"
  MaxAge: 3600