// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks_repository

import (
	context "context"

	model "github.com/nocturna-ta/ums/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// KPUBranchRepository is an autogenerated mock type for the KPUBranchRepository type
type KPUBranchRepository struct {
	mock.Mock
}

// GetAllKPUBranch provides a mock function with given fields: ctx
func (_m *KPUBranchRepository) GetAllKPUBranch(ctx context.Context) ([]model.KPUBranch, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllKPUBranch")
	}

	var r0 []model.KPUBranch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.KPUBranch, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.KPUBranch); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.KPUBranch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKPUBranchByAddress provides a mock function with given fields: ctx, address
func (_m *KPUBranchRepository) GetKPUBranchByAddress(ctx context.Context, address string) (*model.KPUBranch, error) {
	ret := _m.Called(ctx, address)

	if len(ret) == 0 {
		panic("no return value specified for GetKPUBranchByAddress")
	}

	var r0 *model.KPUBranch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.KPUBranch, error)); ok {
		return rf(ctx, address)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.KPUBranch); ok {
		r0 = rf(ctx, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.KPUBranch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertKPUBranch provides a mock function with given fields: ctx, kpuBranch, signedTransaction
func (_m *KPUBranchRepository) InsertKPUBranch(ctx context.Context, kpuBranch *model.KPUBranch, signedTransaction string) error {
	ret := _m.Called(ctx, kpuBranch, signedTransaction)

	if len(ret) == 0 {
		panic("no return value specified for InsertKPUBranch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.KPUBranch, string) error); ok {
		r0 = rf(ctx, kpuBranch, signedTransaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewKPUBranchRepository creates a new instance of KPUBranchRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKPUBranchRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *KPUBranchRepository {
	mock := &KPUBranchRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
