// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks_repository

import (
	context "context"

	model "github.com/nocturna-ta/ums/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// KPUKotaRepository is an autogenerated mock type for the KPUKotaRepository type
type KPUKotaRepository struct {
	mock.Mock
}

// GetAllKPUKota provides a mock function with given fields: ctx
func (_m *KPUKotaRepository) GetAllKPUKota(ctx context.Context) ([]model.KPUKota, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllKPUKota")
	}

	var r0 []model.KPUKota
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.KPUKota, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.KPUKota); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.KPUKota)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKPUKotaByAddress provides a mock function with given fields: ctx, address
func (_m *KPUKotaRepository) GetKPUKotaByAddress(ctx context.Context, address string) (*model.KPUKota, error) {
	ret := _m.Called(ctx, address)

	if len(ret) == 0 {
		panic("no return value specified for GetKPUKotaByAddress")
	}

	var r0 *model.KPUKota
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.KPUKota, error)); ok {
		return rf(ctx, address)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.KPUKota); ok {
		r0 = rf(ctx, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.KPUKota)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertKPUKota provides a mock function with given fields: ctx, kpu, signedTransaction
func (_m *KPUKotaRepository) InsertKPUKota(ctx context.Context, kpu *model.KPUKota, signedTransaction string) error {
	ret := _m.Called(ctx, kpu, signedTransaction)

	if len(ret) == 0 {
		panic("no return value specified for InsertKPUKota")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.KPUKota, string) error); ok {
		r0 = rf(ctx, kpu, signedTransaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewKPUKotaRepository creates a new instance of KPUKotaRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKPUKotaRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *KPUKotaRepository {
	mock := &KPUKotaRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
