// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks_repository

import (
	context "context"

	model "github.com/nocturna-ta/ums/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// KPUKotaRepository is an autogenerated mock type for the KPUKotaRepository type
type KPUKotaRepository struct {
	mock.Mock
}

// GetAllKPUKota provides a mock function with given fields: ctx
func (_m *KPUKotaRepository) GetAllKPUKota(ctx context.Context) (*[]model.KPUKota, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllKPUKota")
	}

	var r0 *[]model.KPUKota
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*[]model.KPUKota, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *[]model.KPUKota); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]model.KPUKota)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKPUKotaByAddress provides a mock function with given fields: ctx, address
func (_m *KPUKotaRepository) GetKPUKotaByAddress(ctx context.Context, address string) (*model.KPUKota, error) {
	ret := _m.Called(ctx, address)

	if len(ret) == 0 {
		panic("no return value specified for GetKPUKotaByAddress")
	}

	var r0 *model.KPUKota
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.KPUKota, error)); ok {
		return rf(ctx, address)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.KPUKota); ok {
		r0 = rf(ctx, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.KPUKota)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKPUKotaByID provides a mock function with given fields: ctx, id
func (_m *KPUKotaRepository) GetKPUKotaByID(ctx context.Context, id uuid.UUID) (*model.KPUKota, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetKPUKotaByID")
	}

	var r0 *model.KPUKota
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.KPUKota, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.KPUKota); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.KPUKota)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKPUKotaByUserID provides a mock function with given fields: ctx, userID
func (_m *KPUKotaRepository) GetKPUKotaByUserID(ctx context.Context, userID uuid.UUID) (*model.KPUKota, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetKPUKotaByUserID")
	}

	var r0 *model.KPUKota
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.KPUKota, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.KPUKota); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.KPUKota)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertKPUKota provides a mock function with given fields: ctx, kpu
func (_m *KPUKotaRepository) InsertKPUKota(ctx context.Context, kpu *model.KPUKota) error {
	ret := _m.Called(ctx, kpu)

	if len(ret) == 0 {
		panic("no return value specified for InsertKPUKota")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.KPUKota) error); ok {
		r0 = rf(ctx, kpu)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendTxKPUKotaBlockchain provides a mock function with given fields: ctx, signedTransaction
func (_m *KPUKotaRepository) SendTxKPUKotaBlockchain(ctx context.Context, signedTransaction string) (string, error) {
	ret := _m.Called(ctx, signedTransaction)

	if len(ret) == 0 {
		panic("no return value specified for SendTxKPUKotaBlockchain")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, signedTransaction)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, signedTransaction)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, signedTransaction)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateKPUKota provides a mock function with given fields: ctx, kpu
func (_m *KPUKotaRepository) UpdateKPUKota(ctx context.Context, kpu *model.KPUKota) error {
	ret := _m.Called(ctx, kpu)

	if len(ret) == 0 {
		panic("no return value specified for UpdateKPUKota")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.KPUKota) error); ok {
		r0 = rf(ctx, kpu)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateKPUKotaPhoto provides a mock function with given fields: ctx, id, photoPath
func (_m *KPUKotaRepository) UpdateKPUKotaPhoto(ctx context.Context, id uuid.UUID, photoPath string) error {
	ret := _m.Called(ctx, id, photoPath)

	if len(ret) == 0 {
		panic("no return value specified for UpdateKPUKotaPhoto")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, id, photoPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewKPUKotaRepository creates a new instance of KPUKotaRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKPUKotaRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *KPUKotaRepository {
	mock := &KPUKotaRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
