// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks_repository

import (
	context "context"

	model "github.com/nocturna-ta/ums/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// KPUProvinsiRepository is an autogenerated mock type for the KPUProvinsiRepository type
type KPUProvinsiRepository struct {
	mock.Mock
}

// GetAllKPUProvinsi provides a mock function with given fields: ctx
func (_m *KPUProvinsiRepository) GetAllKPUProvinsi(ctx context.Context) ([]model.KPUProvinsi, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllKPUProvinsi")
	}

	var r0 []model.KPUProvinsi
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.KPUProvinsi, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.KPUProvinsi); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.KPUProvinsi)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKPUProvinsiByAddress provides a mock function with given fields: ctx, address
func (_m *KPUProvinsiRepository) GetKPUProvinsiByAddress(ctx context.Context, address string) (*model.KPUProvinsi, error) {
	ret := _m.Called(ctx, address)

	if len(ret) == 0 {
		panic("no return value specified for GetKPUProvinsiByAddress")
	}

	var r0 *model.KPUProvinsi
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.KPUProvinsi, error)); ok {
		return rf(ctx, address)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.KPUProvinsi); ok {
		r0 = rf(ctx, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.KPUProvinsi)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertKPUProvinsi provides a mock function with given fields: ctx, kpu, signedTransaction
func (_m *KPUProvinsiRepository) InsertKPUProvinsi(ctx context.Context, kpu *model.KPUProvinsi, signedTransaction string) error {
	ret := _m.Called(ctx, kpu, signedTransaction)

	if len(ret) == 0 {
		panic("no return value specified for InsertKPUProvinsi")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.KPUProvinsi, string) error); ok {
		r0 = rf(ctx, kpu, signedTransaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewKPUProvinsiRepository creates a new instance of KPUProvinsiRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKPUProvinsiRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *KPUProvinsiRepository {
	mock := &KPUProvinsiRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
