// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks_repository

import (
	context "context"

	model "github.com/nocturna-ta/ums/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// KPUProvinsiRepository is an autogenerated mock type for the KPUProvinsiRepository type
type KPUProvinsiRepository struct {
	mock.Mock
}

// GetAllKPUProvinsi provides a mock function with given fields: ctx
func (_m *KPUProvinsiRepository) GetAllKPUProvinsi(ctx context.Context) ([]model.KPUProvinsi, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllKPUProvinsi")
	}

	var r0 []model.KPUProvinsi
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.KPUProvinsi, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.KPUProvinsi); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.KPUProvinsi)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKPUProvinsiByAddress provides a mock function with given fields: ctx, address
func (_m *KPUProvinsiRepository) GetKPUProvinsiByAddress(ctx context.Context, address string) (*model.KPUProvinsi, error) {
	ret := _m.Called(ctx, address)

	if len(ret) == 0 {
		panic("no return value specified for GetKPUProvinsiByAddress")
	}

	var r0 *model.KPUProvinsi
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.KPUProvinsi, error)); ok {
		return rf(ctx, address)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.KPUProvinsi); ok {
		r0 = rf(ctx, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.KPUProvinsi)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKPUProvinsiByID provides a mock function with given fields: ctx, id
func (_m *KPUProvinsiRepository) GetKPUProvinsiByID(ctx context.Context, id uuid.UUID) (*model.KPUProvinsi, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetKPUProvinsiByID")
	}

	var r0 *model.KPUProvinsi
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.KPUProvinsi, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.KPUProvinsi); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.KPUProvinsi)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKPUProvinsiByUserID provides a mock function with given fields: ctx, userID
func (_m *KPUProvinsiRepository) GetKPUProvinsiByUserID(ctx context.Context, userID uuid.UUID) (*model.KPUProvinsi, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetKPUProvinsiByUserID")
	}

	var r0 *model.KPUProvinsi
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.KPUProvinsi, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.KPUProvinsi); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.KPUProvinsi)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertKPUProvinsi provides a mock function with given fields: ctx, kpu
func (_m *KPUProvinsiRepository) InsertKPUProvinsi(ctx context.Context, kpu *model.KPUProvinsi) error {
	ret := _m.Called(ctx, kpu)

	if len(ret) == 0 {
		panic("no return value specified for InsertKPUProvinsi")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.KPUProvinsi) error); ok {
		r0 = rf(ctx, kpu)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendTxKPUProvinsiBlockchain provides a mock function with given fields: ctx, signedTransaction
func (_m *KPUProvinsiRepository) SendTxKPUProvinsiBlockchain(ctx context.Context, signedTransaction string) (string, error) {
	ret := _m.Called(ctx, signedTransaction)

	if len(ret) == 0 {
		panic("no return value specified for SendTxKPUProvinsiBlockchain")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, signedTransaction)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, signedTransaction)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, signedTransaction)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateKPUProvinsi provides a mock function with given fields: ctx, kpu
func (_m *KPUProvinsiRepository) UpdateKPUProvinsi(ctx context.Context, kpu *model.KPUProvinsi) error {
	ret := _m.Called(ctx, kpu)

	if len(ret) == 0 {
		panic("no return value specified for UpdateKPUProvinsi")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.KPUProvinsi) error); ok {
		r0 = rf(ctx, kpu)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateKPUProvinsiPhoto provides a mock function with given fields: ctx, id, photoPath
func (_m *KPUProvinsiRepository) UpdateKPUProvinsiPhoto(ctx context.Context, id uuid.UUID, photoPath string) error {
	ret := _m.Called(ctx, id, photoPath)

	if len(ret) == 0 {
		panic("no return value specified for UpdateKPUProvinsiPhoto")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, id, photoPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewKPUProvinsiRepository creates a new instance of KPUProvinsiRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKPUProvinsiRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *KPUProvinsiRepository {
	mock := &KPUProvinsiRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
