// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks_repository

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UserStatisticRepository is an autogenerated mock type for the UserStatisticRepository type
type UserStatisticRepository struct {
	mock.Mock
}

// GetCountDPTByStatus provides a mock function with given fields: ctx, status, region
func (_m *UserStatisticRepository) GetCountDPTByStatus(ctx context.Context, status string, region *string) (int, error) {
	ret := _m.Called(ctx, status, region)

	if len(ret) == 0 {
		panic("no return value specified for GetCountDPTByStatus")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string) (int, error)); ok {
		return rf(ctx, status, region)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *string) int); ok {
		r0 = rf(ctx, status, region)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *string) error); ok {
		r1 = rf(ctx, status, region)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDPTNotVoted provides a mock function with given fields: ctx, region
func (_m *UserStatisticRepository) GetDPTNotVoted(ctx context.Context, region *string) (int, error) {
	ret := _m.Called(ctx, region)

	if len(ret) == 0 {
		panic("no return value specified for GetDPTNotVoted")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *string) (int, error)); ok {
		return rf(ctx, region)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *string) int); ok {
		r0 = rf(ctx, region)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *string) error); ok {
		r1 = rf(ctx, region)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDPTTotal provides a mock function with given fields: ctx, region
func (_m *UserStatisticRepository) GetDPTTotal(ctx context.Context, region *string) (int, error) {
	ret := _m.Called(ctx, region)

	if len(ret) == 0 {
		panic("no return value specified for GetDPTTotal")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *string) (int, error)); ok {
		return rf(ctx, region)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *string) int); ok {
		r0 = rf(ctx, region)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *string) error); ok {
		r1 = rf(ctx, region)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDPTVoted provides a mock function with given fields: ctx, region
func (_m *UserStatisticRepository) GetDPTVoted(ctx context.Context, region *string) (int, error) {
	ret := _m.Called(ctx, region)

	if len(ret) == 0 {
		panic("no return value specified for GetDPTVoted")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *string) (int, error)); ok {
		return rf(ctx, region)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *string) int); ok {
		r0 = rf(ctx, region)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *string) error); ok {
		r1 = rf(ctx, region)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDistrictCount provides a mock function with given fields: ctx
func (_m *UserStatisticRepository) GetDistrictCount(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDistrictCount")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKPUKotaApprovedUsers provides a mock function with given fields: ctx
func (_m *UserStatisticRepository) GetKPUKotaApprovedUsers(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetKPUKotaApprovedUsers")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKPUKotaStaff provides a mock function with given fields: ctx, region
func (_m *UserStatisticRepository) GetKPUKotaStaff(ctx context.Context, region *string) (int, error) {
	ret := _m.Called(ctx, region)

	if len(ret) == 0 {
		panic("no return value specified for GetKPUKotaStaff")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *string) (int, error)); ok {
		return rf(ctx, region)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *string) int); ok {
		r0 = rf(ctx, region)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *string) error); ok {
		r1 = rf(ctx, region)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKPUProvinsiApprovedUsers provides a mock function with given fields: ctx
func (_m *UserStatisticRepository) GetKPUProvinsiApprovedUsers(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetKPUProvinsiApprovedUsers")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKPUProvinsiStaff provides a mock function with given fields: ctx, region
func (_m *UserStatisticRepository) GetKPUProvinsiStaff(ctx context.Context, region *string) (int, error) {
	ret := _m.Called(ctx, region)

	if len(ret) == 0 {
		panic("no return value specified for GetKPUProvinsiStaff")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *string) (int, error)); ok {
		return rf(ctx, region)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *string) int); ok {
		r0 = rf(ctx, region)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *string) error); ok {
		r1 = rf(ctx, region)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProvinceCount provides a mock function with given fields: ctx
func (_m *UserStatisticRepository) GetProvinceCount(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetProvinceCount")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserStatisticRepository creates a new instance of UserStatisticRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserStatisticRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserStatisticRepository {
	mock := &UserStatisticRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
