// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks_repository

import (
	context "context"

	model "github.com/nocturna-ta/ums/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// UserLogRepository is an autogenerated mock type for the UserLogRepository type
type UserLogRepository struct {
	mock.Mock
}

// GetUserLogs provides a mock function with given fields: ctx, limit, offset
func (_m *UserLogRepository) GetUserLogs(ctx context.Context, limit int, offset int) ([]model.UserLogs, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetUserLogs")
	}

	var r0 []model.UserLogs
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]model.UserLogs, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []model.UserLogs); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserLogs)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertLog provides a mock function with given fields: ctx, log
func (_m *UserLogRepository) InsertLog(ctx context.Context, log *model.UserLogs) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for InsertLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserLogs) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserLogRepository creates a new instance of UserLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserLogRepository {
	mock := &UserLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
