// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks_repository

import (
	context "context"

	model "github.com/nocturna-ta/ums/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// VoterRepository is an autogenerated mock type for the VoterRepository type
type VoterRepository struct {
	mock.Mock
}

// GetAllVoter provides a mock function with given fields: ctx
func (_m *VoterRepository) GetAllVoter(ctx context.Context) ([]model.Voter, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllVoter")
	}

	var r0 []model.Voter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Voter, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Voter); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Voter)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVoterByAddress provides a mock function with given fields: ctx, address
func (_m *VoterRepository) GetVoterByAddress(ctx context.Context, address string) (*model.Voter, error) {
	ret := _m.Called(ctx, address)

	if len(ret) == 0 {
		panic("no return value specified for GetVoterByAddress")
	}

	var r0 *model.Voter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Voter, error)); ok {
		return rf(ctx, address)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Voter); ok {
		r0 = rf(ctx, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Voter)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVoterByID provides a mock function with given fields: ctx, id
func (_m *VoterRepository) GetVoterByID(ctx context.Context, id uuid.UUID) (*model.Voter, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetVoterByID")
	}

	var r0 *model.Voter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Voter, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Voter); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Voter)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVoterByNIK provides a mock function with given fields: ctx, nik
func (_m *VoterRepository) GetVoterByNIK(ctx context.Context, nik string) (*model.Voter, error) {
	ret := _m.Called(ctx, nik)

	if len(ret) == 0 {
		panic("no return value specified for GetVoterByNIK")
	}

	var r0 *model.Voter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Voter, error)); ok {
		return rf(ctx, nik)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Voter); ok {
		r0 = rf(ctx, nik)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Voter)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, nik)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVoterByRegion provides a mock function with given fields: ctx, region
func (_m *VoterRepository) GetVoterByRegion(ctx context.Context, region string) ([]model.Voter, error) {
	ret := _m.Called(ctx, region)

	if len(ret) == 0 {
		panic("no return value specified for GetVoterByRegion")
	}

	var r0 []model.Voter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.Voter, error)); ok {
		return rf(ctx, region)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.Voter); ok {
		r0 = rf(ctx, region)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Voter)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, region)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVoterByUserID provides a mock function with given fields: ctx, userID
func (_m *VoterRepository) GetVoterByUserID(ctx context.Context, userID uuid.UUID) (*model.Voter, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetVoterByUserID")
	}

	var r0 *model.Voter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Voter, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Voter); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Voter)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertVoter provides a mock function with given fields: ctx, voter
func (_m *VoterRepository) InsertVoter(ctx context.Context, voter *model.Voter) error {
	ret := _m.Called(ctx, voter)

	if len(ret) == 0 {
		panic("no return value specified for InsertVoter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Voter) error); ok {
		r0 = rf(ctx, voter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendTxVoterBlockchain provides a mock function with given fields: ctx, signedTransaction
func (_m *VoterRepository) SendTxVoterBlockchain(ctx context.Context, signedTransaction string) (string, error) {
	ret := _m.Called(ctx, signedTransaction)

	if len(ret) == 0 {
		panic("no return value specified for SendTxVoterBlockchain")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, signedTransaction)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, signedTransaction)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, signedTransaction)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateVoter provides a mock function with given fields: ctx, voter
func (_m *VoterRepository) UpdateVoter(ctx context.Context, voter *model.Voter) error {
	ret := _m.Called(ctx, voter)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVoter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Voter) error); ok {
		r0 = rf(ctx, voter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewVoterRepository creates a new instance of VoterRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVoterRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VoterRepository {
	mock := &VoterRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
