// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks_usecases

import (
	context "context"

	request "github.com/nocturna-ta/ums/internal/usecases/request"
	mock "github.com/stretchr/testify/mock"

	response "github.com/nocturna-ta/ums/internal/usecases/response"
)

// AuthUseCases is an autogenerated mock type for the AuthUseCases type
type AuthUseCases struct {
	mock.Mock
}

// ValidateAuthorization provides a mock function with given fields: ctx, req
func (_m *AuthUseCases) ValidateAuthorization(ctx context.Context, req *request.ValidateAuthorizationRequest) (*response.ValidateAuthorizationResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAuthorization")
	}

	var r0 *response.ValidateAuthorizationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.ValidateAuthorizationRequest) (*response.ValidateAuthorizationResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.ValidateAuthorizationRequest) *response.ValidateAuthorizationResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ValidateAuthorizationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.ValidateAuthorizationRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthUseCases creates a new instance of AuthUseCases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthUseCases(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthUseCases {
	mock := &AuthUseCases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
