// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks_usecases

import (
	context "context"

	request "github.com/nocturna-ta/ums/internal/usecases/request"
	mock "github.com/stretchr/testify/mock"

	response "github.com/nocturna-ta/ums/internal/usecases/response"
)

// KPUBranchUseCases is an autogenerated mock type for the KPUBranchUseCases type
type KPUBranchUseCases struct {
	mock.Mock
}

// GetAllKPUBranch provides a mock function with given fields: ctx
func (_m *KPUBranchUseCases) GetAllKPUBranch(ctx context.Context) (*[]response.KPUBranchResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllKPUBranch")
	}

	var r0 *[]response.KPUBranchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*[]response.KPUBranchResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *[]response.KPUBranchResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]response.KPUBranchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKPUBranchByAddress provides a mock function with given fields: ctx
func (_m *KPUBranchUseCases) GetKPUBranchByAddress(ctx context.Context) (*response.KPUBranchResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetKPUBranchByAddress")
	}

	var r0 *response.KPUBranchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*response.KPUBranchResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *response.KPUBranchResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.KPUBranchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterKPUBranch provides a mock function with given fields: ctx, req
func (_m *KPUBranchUseCases) RegisterKPUBranch(ctx context.Context, req *request.KPUBranchRegistrationRequest) (*response.KPUBranchRegistrationResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RegisterKPUBranch")
	}

	var r0 *response.KPUBranchRegistrationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.KPUBranchRegistrationRequest) (*response.KPUBranchRegistrationResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.KPUBranchRegistrationRequest) *response.KPUBranchRegistrationResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.KPUBranchRegistrationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.KPUBranchRegistrationRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewKPUBranchUseCases creates a new instance of KPUBranchUseCases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKPUBranchUseCases(t interface {
	mock.TestingT
	Cleanup(func())
}) *KPUBranchUseCases {
	mock := &KPUBranchUseCases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
