// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks_usecases

import (
	context "context"

	request "github.com/nocturna-ta/ums/internal/usecases/request"
	mock "github.com/stretchr/testify/mock"

	response "github.com/nocturna-ta/ums/internal/usecases/response"
)

// KPUKotaUseCases is an autogenerated mock type for the KPUKotaUseCases type
type KPUKotaUseCases struct {
	mock.Mock
}

// GetAllKPUKota provides a mock function with given fields: ctx
func (_m *KPUKotaUseCases) GetAllKPUKota(ctx context.Context) (*[]response.KPUKotaResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllKPUKota")
	}

	var r0 *[]response.KPUKotaResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*[]response.KPUKotaResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *[]response.KPUKotaResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]response.KPUKotaResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKPUKotaByAddress provides a mock function with given fields: ctx
func (_m *KPUKotaUseCases) GetKPUKotaByAddress(ctx context.Context) (*response.KPUKotaResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetKPUKotaByAddress")
	}

	var r0 *response.KPUKotaResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*response.KPUKotaResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *response.KPUKotaResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.KPUKotaResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterKPUKota provides a mock function with given fields: ctx, req
func (_m *KPUKotaUseCases) RegisterKPUKota(ctx context.Context, req *request.KPUKotaRegistrationRequest) (*response.KPUKotaRegistrationResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RegisterKPUKota")
	}

	var r0 *response.KPUKotaRegistrationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.KPUKotaRegistrationRequest) (*response.KPUKotaRegistrationResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.KPUKotaRegistrationRequest) *response.KPUKotaRegistrationResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.KPUKotaRegistrationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.KPUKotaRegistrationRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewKPUKotaUseCases creates a new instance of KPUKotaUseCases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKPUKotaUseCases(t interface {
	mock.TestingT
	Cleanup(func())
}) *KPUKotaUseCases {
	mock := &KPUKotaUseCases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
