// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks_usecases

import (
	context "context"
	io "io"

	http "github.com/nocturna-ta/golib/http"

	mock "github.com/stretchr/testify/mock"

	request "github.com/nocturna-ta/ums/internal/usecases/request"

	response "github.com/nocturna-ta/ums/internal/usecases/response"

	uuid "github.com/google/uuid"
)

// KPUKotaUseCases is an autogenerated mock type for the KPUKotaUseCases type
type KPUKotaUseCases struct {
	mock.Mock
}

// GetAllKPUKota provides a mock function with given fields: ctx
func (_m *KPUKotaUseCases) GetAllKPUKota(ctx context.Context) (*[]response.KPUKotaResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllKPUKota")
	}

	var r0 *[]response.KPUKotaResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*[]response.KPUKotaResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *[]response.KPUKotaResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]response.KPUKotaResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKPUKotaByAddress provides a mock function with given fields: ctx
func (_m *KPUKotaUseCases) GetKPUKotaByAddress(ctx context.Context) (*response.KPUKotaResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetKPUKotaByAddress")
	}

	var r0 *response.KPUKotaResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*response.KPUKotaResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *response.KPUKotaResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.KPUKotaResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKPUKotaByID provides a mock function with given fields: ctx, id
func (_m *KPUKotaUseCases) GetKPUKotaByID(ctx context.Context, id uuid.UUID) (*response.KPUKotaResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetKPUKotaByID")
	}

	var r0 *response.KPUKotaResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*response.KPUKotaResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *response.KPUKotaResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.KPUKotaResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKPUKotaByUserID provides a mock function with given fields: ctx
func (_m *KPUKotaUseCases) GetKPUKotaByUserID(ctx context.Context) (*response.KPUKotaResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetKPUKotaByUserID")
	}

	var r0 *response.KPUKotaResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*response.KPUKotaResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *response.KPUKotaResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.KPUKotaResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKPUKotaPhoto provides a mock function with given fields: ctx
func (_m *KPUKotaUseCases) GetKPUKotaPhoto(ctx context.Context) (*http.File, string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetKPUKotaPhoto")
	}

	var r0 *http.File
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) (*http.File, string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *http.File); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.File)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) string); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RegisterKPUKota provides a mock function with given fields: ctx, req
func (_m *KPUKotaUseCases) RegisterKPUKota(ctx context.Context, req *request.KPUKotaRegistrationRequest) (*response.KPUKotaRegistrationResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RegisterKPUKota")
	}

	var r0 *response.KPUKotaRegistrationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.KPUKotaRegistrationRequest) (*response.KPUKotaRegistrationResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.KPUKotaRegistrationRequest) *response.KPUKotaRegistrationResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.KPUKotaRegistrationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.KPUKotaRegistrationRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateKPUKota provides a mock function with given fields: ctx, updateRequest
func (_m *KPUKotaUseCases) UpdateKPUKota(ctx context.Context, updateRequest *request.KPUKotaUpdateRequest) (*response.KPUKotaResponse, error) {
	ret := _m.Called(ctx, updateRequest)

	if len(ret) == 0 {
		panic("no return value specified for UpdateKPUKota")
	}

	var r0 *response.KPUKotaResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.KPUKotaUpdateRequest) (*response.KPUKotaResponse, error)); ok {
		return rf(ctx, updateRequest)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.KPUKotaUpdateRequest) *response.KPUKotaResponse); ok {
		r0 = rf(ctx, updateRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.KPUKotaResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.KPUKotaUpdateRequest) error); ok {
		r1 = rf(ctx, updateRequest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UploadKPUKotaPhoto provides a mock function with given fields: ctx, fileData, fileName
func (_m *KPUKotaUseCases) UploadKPUKotaPhoto(ctx context.Context, fileData io.Reader, fileName string) error {
	ret := _m.Called(ctx, fileData, fileName)

	if len(ret) == 0 {
		panic("no return value specified for UploadKPUKotaPhoto")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, string) error); ok {
		r0 = rf(ctx, fileData, fileName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewKPUKotaUseCases creates a new instance of KPUKotaUseCases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKPUKotaUseCases(t interface {
	mock.TestingT
	Cleanup(func())
}) *KPUKotaUseCases {
	mock := &KPUKotaUseCases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
