// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks_usecases

import (
	context "context"

	request "github.com/nocturna-ta/ums/internal/usecases/request"
	mock "github.com/stretchr/testify/mock"

	response "github.com/nocturna-ta/ums/internal/usecases/response"
)

// KPUProvinsiUseCases is an autogenerated mock type for the KPUProvinsiUseCases type
type KPUProvinsiUseCases struct {
	mock.Mock
}

// GetAllKPUProvinsi provides a mock function with given fields: ctx
func (_m *KPUProvinsiUseCases) GetAllKPUProvinsi(ctx context.Context) (*[]response.KPUProvinsiResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllKPUProvinsi")
	}

	var r0 *[]response.KPUProvinsiResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*[]response.KPUProvinsiResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *[]response.KPUProvinsiResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]response.KPUProvinsiResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKPUProvinsiByAddress provides a mock function with given fields: ctx
func (_m *KPUProvinsiUseCases) GetKPUProvinsiByAddress(ctx context.Context) (*response.KPUProvinsiResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetKPUProvinsiByAddress")
	}

	var r0 *response.KPUProvinsiResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*response.KPUProvinsiResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *response.KPUProvinsiResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.KPUProvinsiResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterKPUProvinsi provides a mock function with given fields: ctx, req
func (_m *KPUProvinsiUseCases) RegisterKPUProvinsi(ctx context.Context, req *request.KPUProvinsiRegistrationRequest) (*response.KPUProvinsiRegistrationResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RegisterKPUProvinsi")
	}

	var r0 *response.KPUProvinsiRegistrationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.KPUProvinsiRegistrationRequest) (*response.KPUProvinsiRegistrationResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.KPUProvinsiRegistrationRequest) *response.KPUProvinsiRegistrationResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.KPUProvinsiRegistrationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.KPUProvinsiRegistrationRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewKPUProvinsiUseCases creates a new instance of KPUProvinsiUseCases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKPUProvinsiUseCases(t interface {
	mock.TestingT
	Cleanup(func())
}) *KPUProvinsiUseCases {
	mock := &KPUProvinsiUseCases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
