// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks_usecases

import (
	context "context"
	io "io"

	http "github.com/nocturna-ta/golib/http"

	mock "github.com/stretchr/testify/mock"

	request "github.com/nocturna-ta/ums/internal/usecases/request"

	response "github.com/nocturna-ta/ums/internal/usecases/response"

	uuid "github.com/google/uuid"
)

// KPUProvinsiUseCases is an autogenerated mock type for the KPUProvinsiUseCases type
type KPUProvinsiUseCases struct {
	mock.Mock
}

// GetAllKPUProvinsi provides a mock function with given fields: ctx
func (_m *KPUProvinsiUseCases) GetAllKPUProvinsi(ctx context.Context) (*[]response.KPUProvinsiResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllKPUProvinsi")
	}

	var r0 *[]response.KPUProvinsiResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*[]response.KPUProvinsiResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *[]response.KPUProvinsiResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]response.KPUProvinsiResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKPUProvinsiByAddress provides a mock function with given fields: ctx
func (_m *KPUProvinsiUseCases) GetKPUProvinsiByAddress(ctx context.Context) (*response.KPUProvinsiResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetKPUProvinsiByAddress")
	}

	var r0 *response.KPUProvinsiResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*response.KPUProvinsiResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *response.KPUProvinsiResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.KPUProvinsiResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKPUProvinsiByID provides a mock function with given fields: ctx, id
func (_m *KPUProvinsiUseCases) GetKPUProvinsiByID(ctx context.Context, id uuid.UUID) (*response.KPUProvinsiResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetKPUProvinsiByID")
	}

	var r0 *response.KPUProvinsiResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*response.KPUProvinsiResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *response.KPUProvinsiResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.KPUProvinsiResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKPUProvinsiByUserID provides a mock function with given fields: ctx
func (_m *KPUProvinsiUseCases) GetKPUProvinsiByUserID(ctx context.Context) (*response.KPUProvinsiResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetKPUProvinsiByUserID")
	}

	var r0 *response.KPUProvinsiResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*response.KPUProvinsiResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *response.KPUProvinsiResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.KPUProvinsiResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKPUProvinsiPhoto provides a mock function with given fields: ctx
func (_m *KPUProvinsiUseCases) GetKPUProvinsiPhoto(ctx context.Context) (*http.File, string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetKPUProvinsiPhoto")
	}

	var r0 *http.File
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) (*http.File, string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *http.File); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.File)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) string); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetKPUPusatByUserID provides a mock function with given fields: ctx
func (_m *KPUProvinsiUseCases) GetKPUPusatByUserID(ctx context.Context) (*response.KPUProvinsiResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetKPUPusatByUserID")
	}

	var r0 *response.KPUProvinsiResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*response.KPUProvinsiResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *response.KPUProvinsiResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.KPUProvinsiResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterKPUProvinsi provides a mock function with given fields: ctx, req
func (_m *KPUProvinsiUseCases) RegisterKPUProvinsi(ctx context.Context, req *request.KPUProvinsiRegistrationRequest) (*response.KPUProvinsiRegistrationResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RegisterKPUProvinsi")
	}

	var r0 *response.KPUProvinsiRegistrationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.KPUProvinsiRegistrationRequest) (*response.KPUProvinsiRegistrationResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.KPUProvinsiRegistrationRequest) *response.KPUProvinsiRegistrationResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.KPUProvinsiRegistrationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.KPUProvinsiRegistrationRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateKPUProvinsi provides a mock function with given fields: ctx, updateRequest
func (_m *KPUProvinsiUseCases) UpdateKPUProvinsi(ctx context.Context, updateRequest *request.KPUProvinsiUpdateRequest) (*response.KPUProvinsiResponse, error) {
	ret := _m.Called(ctx, updateRequest)

	if len(ret) == 0 {
		panic("no return value specified for UpdateKPUProvinsi")
	}

	var r0 *response.KPUProvinsiResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.KPUProvinsiUpdateRequest) (*response.KPUProvinsiResponse, error)); ok {
		return rf(ctx, updateRequest)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.KPUProvinsiUpdateRequest) *response.KPUProvinsiResponse); ok {
		r0 = rf(ctx, updateRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.KPUProvinsiResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.KPUProvinsiUpdateRequest) error); ok {
		r1 = rf(ctx, updateRequest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UploadKPUProvinsiPhoto provides a mock function with given fields: ctx, fileData, fileName
func (_m *KPUProvinsiUseCases) UploadKPUProvinsiPhoto(ctx context.Context, fileData io.Reader, fileName string) error {
	ret := _m.Called(ctx, fileData, fileName)

	if len(ret) == 0 {
		panic("no return value specified for UploadKPUProvinsiPhoto")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, string) error); ok {
		r0 = rf(ctx, fileData, fileName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewKPUProvinsiUseCases creates a new instance of KPUProvinsiUseCases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKPUProvinsiUseCases(t interface {
	mock.TestingT
	Cleanup(func())
}) *KPUProvinsiUseCases {
	mock := &KPUProvinsiUseCases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
