// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks_usecases

import (
	context "context"

	response "github.com/nocturna-ta/ums/internal/usecases/response"
	mock "github.com/stretchr/testify/mock"
)

// UserLogUseCases is an autogenerated mock type for the UserLogUseCases type
type UserLogUseCases struct {
	mock.Mock
}

// GetAllUserLog provides a mock function with given fields: ctx, limit, offset
func (_m *UserLogUseCases) GetAllUserLog(ctx context.Context, limit int, offset int) (*[]response.UserLogResponse, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUserLog")
	}

	var r0 *[]response.UserLogResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*[]response.UserLogResponse, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *[]response.UserLogResponse); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]response.UserLogResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserLogUseCases creates a new instance of UserLogUseCases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserLogUseCases(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserLogUseCases {
	mock := &UserLogUseCases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
