// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks_usecases

import (
	context "context"

	response "github.com/nocturna-ta/ums/internal/usecases/response"
	mock "github.com/stretchr/testify/mock"
)

// UserStatisticUseCases is an autogenerated mock type for the UserStatisticUseCases type
type UserStatisticUseCases struct {
	mock.Mock
}

// GetApprovedDPTStatistic provides a mock function with given fields: ctx, region
func (_m *UserStatisticUseCases) GetApprovedDPTStatistic(ctx context.Context, region string) (*response.ApprovedDPTResponse, error) {
	ret := _m.Called(ctx, region)

	if len(ret) == 0 {
		panic("no return value specified for GetApprovedDPTStatistic")
	}

	var r0 *response.ApprovedDPTResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*response.ApprovedDPTResponse, error)); ok {
		return rf(ctx, region)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *response.ApprovedDPTResponse); ok {
		r0 = rf(ctx, region)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ApprovedDPTResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, region)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKotaInformationDPTStatistic provides a mock function with given fields: ctx
func (_m *UserStatisticUseCases) GetKotaInformationDPTStatistic(ctx context.Context) ([]*response.DPTInformationResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetKotaInformationDPTStatistic")
	}

	var r0 []*response.DPTInformationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*response.DPTInformationResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*response.DPTInformationResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*response.DPTInformationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPendingDPTStatistic provides a mock function with given fields: ctx, region
func (_m *UserStatisticUseCases) GetPendingDPTStatistic(ctx context.Context, region string) (*response.PendingDPTResponse, error) {
	ret := _m.Called(ctx, region)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingDPTStatistic")
	}

	var r0 *response.PendingDPTResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*response.PendingDPTResponse, error)); ok {
		return rf(ctx, region)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *response.PendingDPTResponse); ok {
		r0 = rf(ctx, region)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.PendingDPTResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, region)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProvinceInformationDPTStatistic provides a mock function with given fields: ctx
func (_m *UserStatisticUseCases) GetProvinceInformationDPTStatistic(ctx context.Context) ([]*response.DPTInformationResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetProvinceInformationDPTStatistic")
	}

	var r0 []*response.DPTInformationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*response.DPTInformationResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*response.DPTInformationResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*response.DPTInformationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRejectedDPTStatistic provides a mock function with given fields: ctx, region
func (_m *UserStatisticUseCases) GetRejectedDPTStatistic(ctx context.Context, region string) (*response.RejectedDPTResponse, error) {
	ret := _m.Called(ctx, region)

	if len(ret) == 0 {
		panic("no return value specified for GetRejectedDPTStatistic")
	}

	var r0 *response.RejectedDPTResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*response.RejectedDPTResponse, error)); ok {
		return rf(ctx, region)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *response.RejectedDPTResponse); ok {
		r0 = rf(ctx, region)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.RejectedDPTResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, region)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStaffKPUKotaStatistic provides a mock function with given fields: ctx, region
func (_m *UserStatisticUseCases) GetStaffKPUKotaStatistic(ctx context.Context, region string) (*response.StaffKPUResponse, error) {
	ret := _m.Called(ctx, region)

	if len(ret) == 0 {
		panic("no return value specified for GetStaffKPUKotaStatistic")
	}

	var r0 *response.StaffKPUResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*response.StaffKPUResponse, error)); ok {
		return rf(ctx, region)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *response.StaffKPUResponse); ok {
		r0 = rf(ctx, region)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.StaffKPUResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, region)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStaffKPUProvinceStatistic provides a mock function with given fields: ctx, region
func (_m *UserStatisticUseCases) GetStaffKPUProvinceStatistic(ctx context.Context, region string) (*response.StaffKPUResponse, error) {
	ret := _m.Called(ctx, region)

	if len(ret) == 0 {
		panic("no return value specified for GetStaffKPUProvinceStatistic")
	}

	var r0 *response.StaffKPUResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*response.StaffKPUResponse, error)); ok {
		return rf(ctx, region)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *response.StaffKPUResponse); ok {
		r0 = rf(ctx, region)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.StaffKPUResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, region)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTotalDPTStatistic provides a mock function with given fields: ctx, region
func (_m *UserStatisticUseCases) GetTotalDPTStatistic(ctx context.Context, region string) (*response.TotalDPTResponse, error) {
	ret := _m.Called(ctx, region)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalDPTStatistic")
	}

	var r0 *response.TotalDPTResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*response.TotalDPTResponse, error)); ok {
		return rf(ctx, region)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *response.TotalDPTResponse); ok {
		r0 = rf(ctx, region)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.TotalDPTResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, region)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVotedStatistic provides a mock function with given fields: ctx, region
func (_m *UserStatisticUseCases) GetVotedStatistic(ctx context.Context, region string) (*response.VotedStatisticResponse, error) {
	ret := _m.Called(ctx, region)

	if len(ret) == 0 {
		panic("no return value specified for GetVotedStatistic")
	}

	var r0 *response.VotedStatisticResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*response.VotedStatisticResponse, error)); ok {
		return rf(ctx, region)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *response.VotedStatisticResponse); ok {
		r0 = rf(ctx, region)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.VotedStatisticResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, region)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserStatisticUseCases creates a new instance of UserStatisticUseCases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserStatisticUseCases(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserStatisticUseCases {
	mock := &UserStatisticUseCases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
