// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks_usecases

import (
	context "context"

	request "github.com/nocturna-ta/ums/internal/usecases/request"
	mock "github.com/stretchr/testify/mock"

	response "github.com/nocturna-ta/ums/internal/usecases/response"
)

// VoterUseCases is an autogenerated mock type for the VoterUseCases type
type VoterUseCases struct {
	mock.Mock
}

// GetAllVoter provides a mock function with given fields: ctx
func (_m *VoterUseCases) GetAllVoter(ctx context.Context) (*[]response.VoterResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllVoter")
	}

	var r0 *[]response.VoterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*[]response.VoterResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *[]response.VoterResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]response.VoterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVoterByAddress provides a mock function with given fields: ctx
func (_m *VoterUseCases) GetVoterByAddress(ctx context.Context) (*response.VoterResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetVoterByAddress")
	}

	var r0 *response.VoterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*response.VoterResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *response.VoterResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.VoterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVoterByNIK provides a mock function with given fields: ctx, nik
func (_m *VoterUseCases) GetVoterByNIK(ctx context.Context, nik string) (*response.VoterResponse, error) {
	ret := _m.Called(ctx, nik)

	if len(ret) == 0 {
		panic("no return value specified for GetVoterByNIK")
	}

	var r0 *response.VoterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*response.VoterResponse, error)); ok {
		return rf(ctx, nik)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *response.VoterResponse); ok {
		r0 = rf(ctx, nik)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.VoterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, nik)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVoterByRegion provides a mock function with given fields: ctx, region
func (_m *VoterUseCases) GetVoterByRegion(ctx context.Context, region string) (*[]response.VoterResponse, error) {
	ret := _m.Called(ctx, region)

	if len(ret) == 0 {
		panic("no return value specified for GetVoterByRegion")
	}

	var r0 *[]response.VoterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*[]response.VoterResponse, error)); ok {
		return rf(ctx, region)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *[]response.VoterResponse); ok {
		r0 = rf(ctx, region)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]response.VoterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, region)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterVoter provides a mock function with given fields: ctx, req
func (_m *VoterUseCases) RegisterVoter(ctx context.Context, req *request.VoterRegistrationRequest) (*response.VoterRegistrationResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RegisterVoter")
	}

	var r0 *response.VoterRegistrationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.VoterRegistrationRequest) (*response.VoterRegistrationResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.VoterRegistrationRequest) *response.VoterRegistrationResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.VoterRegistrationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.VoterRegistrationRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVoterUseCases creates a new instance of VoterUseCases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVoterUseCases(t interface {
	mock.TestingT
	Cleanup(func())
}) *VoterUseCases {
	mock := &VoterUseCases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
