// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks_interfaces

import (
	context "context"

	jwt "github.com/golang-jwt/jwt/v5"
	jwtsvc "github.com/nocturna-ta/ums/internal/interfaces/jwtsvc"

	mock "github.com/stretchr/testify/mock"
)

// JWT is an autogenerated mock type for the JWT type
type JWT struct {
	mock.Mock
}

// GenerateToken provides a mock function with given fields: ctx, claims
func (_m *JWT) GenerateToken(ctx context.Context, claims jwt.Claims) (*string, error) {
	ret := _m.Called(ctx, claims)

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 *string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, jwt.Claims) (*string, error)); ok {
		return rf(ctx, claims)
	}
	if rf, ok := ret.Get(0).(func(context.Context, jwt.Claims) *string); ok {
		r0 = rf(ctx, claims)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, jwt.Claims) error); ok {
		r1 = rf(ctx, claims)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Validate provides a mock function with given fields: ctx, token, claimType
func (_m *JWT) Validate(ctx context.Context, token string, claimType jwtsvc.ClaimType) (jwt.Claims, error) {
	ret := _m.Called(ctx, token, claimType)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 jwt.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, jwtsvc.ClaimType) (jwt.Claims, error)); ok {
		return rf(ctx, token, claimType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, jwtsvc.ClaimType) jwt.Claims); ok {
		r0 = rf(ctx, token, claimType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jwt.Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, jwtsvc.ClaimType) error); ok {
		r1 = rf(ctx, token, claimType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewJWT creates a new instance of JWT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJWT(t interface {
	mock.TestingT
	Cleanup(func())
}) *JWT {
	mock := &JWT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
