basePath: /
definitions:
  controller.errorResponse:
    properties:
      error_code:
        type: integer
      error_message:
        type: string
    type: object
  controller.jsonResponse:
    properties:
      code:
        type: integer
      data: {}
      error:
        $ref: '#/definitions/controller.errorResponse'
      message:
        type: string
    type: object
  request.KPUKotaRegistrationRequest:
    properties:
      address:
        type: string
      is_active:
        type: boolean
      name:
        type: string
      region:
        type: string
      signed_transaction:
        type: string
    type: object
  request.KPUProvinsiRegistrationRequest:
    properties:
      address:
        type: string
      is_active:
        type: boolean
      name:
        type: string
      region:
        type: string
      signed_transaction:
        type: string
    type: object
  request.UserChangePasswordRequest:
    properties:
      confirm:
        type: string
      new:
        type: string
      old:
        type: string
    type: object
  request.UserLoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  request.UserRegistrationRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  request.UserUpdateRequest:
    properties:
      username:
        type: string
    type: object
  request.VoterRegistrationRequest:
    properties:
      is_registered:
        type: boolean
      nik:
        type: string
      region:
        type: string
      signed_transaction:
        type: string
      voter_address:
        type: string
    type: object
  response.KPUKotaRegistrationResponse:
    properties:
      address:
        type: string
      is_active:
        type: boolean
    type: object
  response.KPUKotaResponse:
    properties:
      address:
        type: string
      id:
        type: string
      is_active:
        type: boolean
      region:
        type: string
    type: object
  response.KPUProvinsiRegistrationResponse:
    properties:
      address:
        type: string
      is_active:
        type: boolean
    type: object
  response.KPUProvinsiResponse:
    properties:
      address:
        type: string
      id:
        type: string
      is_active:
        type: boolean
      region:
        type: string
    type: object
  response.UserLoginResponse:
    properties:
      expires_at:
        type: string
      token:
        type: string
    type: object
  response.UserRegistrationResponse:
    properties:
      email:
        type: string
      id:
        type: string
      username:
        type: string
    type: object
  response.UserResponse:
    properties:
      id:
        type: string
      username:
        type: string
    type: object
  response.VoterRegistrationResponse:
    properties:
      is_registered:
        type: boolean
    type: object
  response.VoterResponse:
    properties:
      has_voted:
        type: boolean
      id:
        type: string
      is_registered:
        type: boolean
      nik:
        type: string
      region:
        type: string
      voter_address:
        type: string
    type: object
info:
  contact: {}
  description: User Management System Service.
  title: UMS Service
  version: 1.0.0
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Ping to check health
      parameters:
      - description: user that make request
        in: header
        name: X-User-Id
        type: string
      - default: web
        description: channel where request comes from
        in: header
        name: X-Channel-Id
        type: string
      - description: request unique identifier
        in: header
        name: X-Request-Id
        type: string
      - description: user account
        in: header
        name: X-Account-Id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.jsonResponse'
      summary: Ping
      tags:
      - Health
  /v1/kpu-kota:
    get:
      consumes:
      - application/json
      description: Get All KPU Kota
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.KPUKotaResponse'
              type: object
      summary: Get All KPU Kota
      tags:
      - kpu_kota
  /v1/kpu-kota/address:
    get:
      consumes:
      - application/json
      description: Get KPU Kota By Address
      parameters:
      - description: User
        in: header
        name: X-User-Id
        type: string
      - description: Address
        in: header
        name: X-Address-Id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.KPUKotaResponse'
              type: object
      summary: Get KPU Kota By Address
      tags:
      - kpu_kota
  /v1/kpu-kota/register:
    post:
      consumes:
      - application/json
      description: Register KPU Kota
      parameters:
      - description: Register Request
        in: body
        name: users
        required: true
        schema:
          $ref: '#/definitions/request.KPUKotaRegistrationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.KPUKotaRegistrationResponse'
              type: object
      summary: Register KPU Kota
      tags:
      - kpu_kota
  /v1/kpu-provinsi:
    get:
      consumes:
      - application/json
      description: Get All KPU Provinsi
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.KPUProvinsiResponse'
              type: object
      summary: Get All KPU Provinsi
      tags:
      - kpu_provinsi
  /v1/kpu-provinsi/address:
    get:
      consumes:
      - application/json
      description: Get KPU Provinsi By Address
      parameters:
      - description: User
        in: header
        name: X-User-Id
        type: string
      - description: Address
        in: header
        name: X-Address-Id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.KPUProvinsiResponse'
              type: object
      summary: Get KPU Provinsi By Address
      tags:
      - kpu_provinsi
  /v1/kpu-provinsi/register:
    post:
      consumes:
      - application/json
      description: Register KPU Provinsi
      parameters:
      - description: Register Request
        in: body
        name: users
        required: true
        schema:
          $ref: '#/definitions/request.KPUProvinsiRegistrationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.KPUProvinsiRegistrationResponse'
              type: object
      summary: Register KPU Provinsi
      tags:
      - kpu_provinsi
  /v1/user/{email}:
    get:
      consumes:
      - application/json
      description: Get user by email
      parameters:
      - description: User email
        in: path
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: User found
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.UserResponse'
              type: object
      summary: Get user by email
      tags:
      - User
  /v1/user/change-password:
    put:
      consumes:
      - application/json
      description: Change user password
      parameters:
      - description: User
        in: header
        name: X-User-Id
        type: string
      - description: Address
        in: header
        name: X-Address-Id
        type: string
      - description: User change password request
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/request.UserChangePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Password changed
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.UserResponse'
              type: object
      summary: Change user password
      tags:
      - User
  /v1/user/login:
    post:
      consumes:
      - application/json
      description: Login user
      parameters:
      - description: User login request
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/request.UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User logged in
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.UserLoginResponse'
              type: object
      summary: Login user
      tags:
      - User
  /v1/user/me:
    get:
      consumes:
      - application/json
      description: Get user by ID
      parameters:
      - description: User
        in: header
        name: X-User-Id
        type: string
      - description: Address
        in: header
        name: X-Address-Id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: User found
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.UserResponse'
              type: object
      summary: Get user by ID
      tags:
      - User
  /v1/user/register:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: User registration request
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/request.UserRegistrationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.UserRegistrationResponse'
              type: object
      summary: Register a new user
      tags:
      - User
  /v1/user/update:
    put:
      consumes:
      - application/json
      description: Update user
      parameters:
      - description: User
        in: header
        name: X-User-Id
        type: string
      - description: Address
        in: header
        name: X-Address-Id
        type: string
      - description: User update request
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/request.UserUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User updated
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.UserResponse'
              type: object
      summary: Update user
      tags:
      - User
  /v1/voter:
    get:
      consumes:
      - application/json
      description: Get All Voter
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.VoterResponse'
              type: object
      summary: Get All Voter
      tags:
      - voters
  /v1/voter/address:
    get:
      consumes:
      - application/json
      description: Get Voter By Address
      parameters:
      - description: User
        in: header
        name: X-User-Id
        type: string
      - description: Address
        in: header
        name: X-Address-Id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.VoterResponse'
              type: object
      summary: Get Voter By Address
      tags:
      - voters
  /v1/voter/nik/{nik}:
    get:
      consumes:
      - application/json
      description: Get Voter By NIK
      parameters:
      - description: NIK
        in: path
        name: nik
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.VoterResponse'
              type: object
      summary: Get Voter By NIK
      tags:
      - voters
  /v1/voter/region/{region}:
    get:
      consumes:
      - application/json
      description: Get Voter By Region
      parameters:
      - description: Region
        in: path
        name: region
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.VoterResponse'
              type: object
      summary: Get Voter By Region
      tags:
      - voters
  /v1/voter/register:
    post:
      consumes:
      - application/json
      description: Register Voter
      parameters:
      - description: Register Request
        in: body
        name: users
        required: true
        schema:
          $ref: '#/definitions/request.VoterRegistrationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.VoterRegistrationResponse'
              type: object
      summary: Register Voter
      tags:
      - voters
swagger: "2.0"
