basePath: /
definitions:
  controller.errorResponse:
    properties:
      error_code:
        type: integer
      error_message:
        type: string
    type: object
  controller.jsonResponse:
    properties:
      code:
        type: integer
      data: {}
      error:
        $ref: '#/definitions/controller.errorResponse'
      message:
        type: string
    type: object
  request.KPUBranchRegistrationRequest:
    properties:
      branch_address:
        type: string
      is_active:
        type: boolean
      name:
        type: string
      region:
        type: string
      signed_transaction:
        type: string
    type: object
  request.UserRegistrationRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  request.UserUpdateRequest:
    properties:
      username:
        type: string
    type: object
  request.VoterRegistrationRequest:
    properties:
      is_registered:
        type: boolean
      nik:
        type: string
      region:
        type: string
      signed_transaction:
        type: string
      voter_address:
        type: string
    type: object
  response.KPUBranchRegistrationResponse:
    properties:
      branch_address:
        type: string
      is_active:
        type: boolean
    type: object
  response.KPUBranchResponse:
    properties:
      branch_address:
        type: string
      id:
        type: string
      is_active:
        type: boolean
      region:
        type: string
    type: object
  response.UserRegistrationResponse:
    properties:
      email:
        type: string
      id:
        type: string
      username:
        type: string
    type: object
  response.UserResponse:
    properties:
      id:
        type: string
      username:
        type: string
    type: object
  response.VoterRegistrationResponse:
    properties:
      is_registered:
        type: boolean
    type: object
  response.VoterResponse:
    properties:
      has_voted:
        type: boolean
      id:
        type: string
      is_registered:
        type: boolean
      nik:
        type: string
      region:
        type: string
      voter_address:
        type: string
    type: object
info:
  contact: {}
  description: User Management System Service.
  title: UMS Service
  version: 1.0.0
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Ping to check health
      parameters:
      - description: user that make request
        in: header
        name: X-User-Id
        type: string
      - default: web
        description: channel where request comes from
        in: header
        name: X-Channel-Id
        type: string
      - description: request unique identifier
        in: header
        name: X-Request-Id
        type: string
      - description: user account
        in: header
        name: X-Account-Id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.jsonResponse'
      summary: Ping
      tags:
      - Health
  /v1/kpu-branch:
    get:
      consumes:
      - application/json
      description: Get All KPU Branch
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.KPUBranchResponse'
              type: object
      summary: Get All KPU Branch
      tags:
      - kpu_branch
  /v1/kpu-branch/address/{address}:
    get:
      consumes:
      - application/json
      description: Get KPU Branch By Address
      parameters:
      - description: Address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.KPUBranchResponse'
              type: object
      summary: Get KPU Branch By Address
      tags:
      - kpu_branch
  /v1/kpu-branch/register:
    post:
      consumes:
      - application/json
      description: Register KPU Branch
      parameters:
      - description: Register Request
        in: body
        name: users
        required: true
        schema:
          $ref: '#/definitions/request.KPUBranchRegistrationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.KPUBranchRegistrationResponse'
              type: object
      summary: Register KPU Branch
      tags:
      - kpu_branch
  /v1/user/{email}:
    get:
      consumes:
      - application/json
      description: Get user by email
      parameters:
      - description: User email
        in: path
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: User found
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.UserResponse'
              type: object
      summary: Get user by email
      tags:
      - User
  /v1/user/id/{id}:
    get:
      consumes:
      - application/json
      description: Get user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: User found
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.UserResponse'
              type: object
      summary: Get user by ID
      tags:
      - User
  /v1/user/register:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: User registration request
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/request.UserRegistrationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.UserRegistrationResponse'
              type: object
      summary: Register a new user
      tags:
      - User
  /v1/user/update/{id}:
    put:
      consumes:
      - application/json
      description: Update user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: User update request
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/request.UserUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User updated
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.UserResponse'
              type: object
      summary: Update user
      tags:
      - User
  /v1/voter:
    get:
      consumes:
      - application/json
      description: Get All Voter
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.VoterResponse'
              type: object
      summary: Get All Voter
      tags:
      - voters
  /v1/voter/{nik}:
    get:
      consumes:
      - application/json
      description: Get Voter By NIK
      parameters:
      - description: NIK
        in: path
        name: nik
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.VoterResponse'
              type: object
      summary: Get Voter By NIK
      tags:
      - voters
  /v1/voter/address/{address}:
    get:
      consumes:
      - application/json
      description: Get Voter By Address
      parameters:
      - description: Address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.VoterResponse'
              type: object
      summary: Get Voter By Address
      tags:
      - voters
  /v1/voter/region/{region}:
    get:
      consumes:
      - application/json
      description: Get Voter By Region
      parameters:
      - description: Region
        in: path
        name: region
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.VoterResponse'
              type: object
      summary: Get Voter By Region
      tags:
      - voters
  /v1/voter/register:
    post:
      consumes:
      - application/json
      description: Register Voter
      parameters:
      - description: Register Request
        in: body
        name: users
        required: true
        schema:
          $ref: '#/definitions/request.VoterRegistrationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.VoterRegistrationResponse'
              type: object
      summary: Register Voter
      tags:
      - voters
swagger: "2.0"
